#!/bin/bash
# run all tests in a pkg/snippet dir
#  eg  (Beware this does a git commit)
#     ./SnippetTest  R/PkgSnippets/dse/1stSnippetTest

#set -e to stop on error?

CHK=$(echo $1 | cut -f2 -d/)
PKG=$(echo $1 | cut -f3 -d/)
SNP=$(echo $1 | cut -f4 -d/)

echo running SnippetTest for ${CHK}/${PKG}/${SNP} 

# only run for snippet changes ( but should run for package version change and R version change )
if [ ""${CHK} != "PkgSnippets" ] ; then exit 0 ; fi

Rscript -e 'if(!"${PKG}" %in% rownames(installed.packages())) { install.packages("${PKG}", dependencies = TRUE) }'

cd ${CHK}/${PKG}/${SNP}

echo -n "" >STATUS_SUMMARY

#Adding date here means the file is always updated when the snippet tests are run, 
#  so travis build number is recorded in git commit comment.
#  Other files are built but if there are no changes then not committed.

date >>STATUS_SUMMARY

for f in `ls *.[rR]` ; do
    Rscript ${f} >${f}out 2>&1;
    x=$?
    echo ${f} exit code $x ;
    git add   ${f}out ;
    if [ 0 -eq $x ]  ; \
     then echo -n ${f}": passed." >>STATUS_SUMMARY  ; \
     else echo -n ${f}": failed." >>STATUS_SUMMARY  ;fi ;
    done

git add   STATUS_SUMMARY

git branch
git status
git commit  -m "Travis build: ${TRAVIS_BUILD_NUMBER}"

exit 0
